### ISSUE TITLE
Slim the template

### ISSUE THREAD

**Issue by afeld** [virtix/open-source-program-template#6]
Hey there-
I wanted to say that this is a great project, and I'm excited to be doing some contributions to the @18F fork (https://18f.github.io/open-source-program/).

One thing that's been bothering me is that there's a lot of information that's duplicated between our site and your template (and presumably all of the other forks). Seems like it might be useful to think of the template as a place to put information/guidelines that would differ between organizations, rather than ones that are generally applicable. As a concrete example, the [Open Source Policy](https://github.com/virtix/open-source-program-template/blob/gh-pages/pages/oss_policy.md) page will almost definitely be tweaked from one organization to another, whereas the [Git workflow](https://github.com/virtix/open-source-program-template/blob/gh-pages/pages/git_workflow.md) document is almost definitely going to be the same for everyone.

How would you feel about splitting the repository, making one site with that information that is "canonical", and this template, which only includes things like the draft policy page, blog posts, etc? Happy to take a first pass/PR at this, if you're open to it.

All of that being said, I'm totally aware that trying to make a canonical _anything_ is potentially misguided.

[![xkcd: Standards](http://imgs.xkcd.com/comics/standards.png)](http://xkcd.com/927/)

Let me know if the proposal doesn't make sense. Thanks!

**Comment by virtix** [comment]
Thanks, @afeld. You articulated well the general idea behind this _template_, which is to have the canonical content reasonably generalized while other content would reflect the specialized needs of other government agencies.  The one at 18f starts to get a bit more specific.  By all means, I'll look for any contributions!  Feel free to reach out to me directly, too, at anyone at if dot io . Thanks again and apologies for the inordinate delay!
